package eu.europa.ec.fisheries.schema.audit.source.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-09-18T16:51:40.247+02:00
 * Generated source version: 3.1.13
 * 
 */
@WebServiceClient(name = "AuditDataSourceQueueService", 
                  wsdlLocation = "file:/C:/git/UVMS-AuditModule-APP/model/src/main/resources/contract/AuditDataSourceService.wsdl",
                  targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1") 
public class AuditDataSourceQueueService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:source.audit.schema.fisheries.ec.europa.eu:v1", "AuditDataSourceQueueService");
    public final static QName DataSourcePortType = new QName("urn:source.audit.schema.fisheries.ec.europa.eu:v1", "DataSourcePortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/git/UVMS-AuditModule-APP/model/src/main/resources/contract/AuditDataSourceService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuditDataSourceQueueService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/git/UVMS-AuditModule-APP/model/src/main/resources/contract/AuditDataSourceService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuditDataSourceQueueService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuditDataSourceQueueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuditDataSourceQueueService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AuditDataSourceQueueService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuditDataSourceQueueService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuditDataSourceQueueService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AuditDataSourcePortType
     */
    @WebEndpoint(name = "DataSourcePortType")
    public AuditDataSourcePortType getDataSourcePortType() {
        return super.getPort(DataSourcePortType, AuditDataSourcePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuditDataSourcePortType
     */
    @WebEndpoint(name = "DataSourcePortType")
    public AuditDataSourcePortType getDataSourcePortType(WebServiceFeature... features) {
        return super.getPort(DataSourcePortType, AuditDataSourcePortType.class, features);
    }

}
