package eu.europa.ec.fisheries.schema.audit.source.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-09-18T16:51:40.238+02:00
 * Generated source version: 3.1.13
 * 
 */
@WebService(targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1", name = "AuditDataSourcePortType")
@XmlSeeAlso({eu.europa.ec.fisheries.schema.audit.search.v1.ObjectFactory.class, eu.europa.ec.fisheries.schema.audit.v1.ObjectFactory.class, eu.europa.ec.fisheries.schema.audit.common.v1.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AuditDataSourcePortType {

    @WebResult(name = "pingResponse", targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "Ping")
    public PingResponse ping(
        @WebParam(partName = "body", name = "pingRequest", targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1")
        PingRequest body
    );

    @WebResult(name = "createAuditLogResponse", targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "CreateAuditLog")
    public CreateAuditLogResponse createAuditLog(
        @WebParam(partName = "body", name = "createAuditLogRequest", targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1")
        CreateAuditLogRequest body
    ) throws AuditException;

    @WebResult(name = "getAuditLogListByQueryResponse", targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetAuditLogList")
    public GetAuditLogListByQueryResponse getAuditLogList(
        @WebParam(partName = "body", name = "getAuditLogListByQueryRequest", targetNamespace = "urn:source.audit.schema.fisheries.ec.europa.eu:v1")
        GetAuditLogListByQueryRequest body
    ) throws AuditException;
}
